version: '3.9'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - EDGE_PORT=4566
    ports:
      - '4566:4566'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
